version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - V:\docker_volume\v1:/code/output
      - V:\docker_volume\v1\static:/code/static
    environment:
      - FLASK_ENV=development
  redis:
    image: "redis:alpine"